### ISSUE TITLE
Videos not playing

### ISSUE THREAD

**Issue by Vineshg** [alexa-samples/alexa-video-multimodal#1]
Hi I have created a Skill in en-In locale. While setup and skill creation and deployment went quite smooth....there are three issues i am facing where any inputs in resolving it will help me. 
1. Videos are not playing in echo show 5. I can see the video skill and linked my account but if i click on video play button or ask alexa to play it doesn't play the video though it takes to the player but screen goes black....is any additional configuration is needed on device or S3 or CDN to stream the video? ( I checked the video s3 url and I could play video in browser though, so video is correctly uploaded. )
2. Alexa is able to recognize the TV series videos but not movie video like "Iron man 2" by using utterance...is there any reason movie videos are not cataloged.
3. I was trying to use the developer console for Alexa for debugging the issues, but for every utterance it says "I couldn’t find any enabled video skills that can do that. Go to the Alexa App to manage your video skills and devices.". But skill is linked fine in Alexa app and in Echo show also it is displaying all the videos not sure why it is not able to debug in developer console. 

Thanks.

**Comment by tuckefre** [comment]
@Vineshg Thanks for your detailed description of the issue.  

1. Is this issue only occurring on Echo Show 5?  Have you tried the skill on other devices?

Also, because you selected en-IN as your locale, your AWS resources were probably provision in the DUB (Ireland) region which is a standard Alexa practice for that locale.  
Depending on where you are located, you may be very far away from the demo content as it is not using any CDN.  The content is served directly from S3 in Ireland in your case.  We were able to reproduce your issue by deploying a skill in a region that is far away from us.  We were also able to resolve the issue by pointing our skill to demo content that is located nearer to us.

Could you try creating an S3 bucket in the region that is nearest to you and copying the `/content` folder from your existing bucket to your new bucket?  You will also need to update the CORs settings for that new bucket.  Here's a CORs setting that allows requests from all origins:

```
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<CORSRule>
    <AllowedOrigin>*</AllowedOrigin>
    <AllowedMethod>GET</AllowedMethod>
    <MaxAgeSeconds>3000</MaxAgeSeconds>
    <ExposeHeader>x-amz-server-side-encryption</ExposeHeader>
    <ExposeHeader>x-amz-request-id</ExposeHeader>
    <ExposeHeader>x-amz-id-2</ExposeHeader>
    <AllowedHeader>*</AllowedHeader>
</CORSRule>
</CORSConfiguration>
```

Lastly, to have your skill read from your new bucket, you'll need to go to the AWS console.  In the AWS console, go to the  AWS Lambda section and modify the environment variable `VIDEO_CONTENT_BUCKET` for your lambda function.  Set the value of that variable to the name of the bucket you created, and then save the lambda function.  Once that is done you should be able to re-invoke the skill and the latency issue should be resolved.

Also consider using a CloudFormation distribution. Implementing that is more involved, but it is a better solution.  Given that you are likely trying to get the skill to play videos for demonstration purposes only, creating a new S3 bucket may be quicker and easier.

2. There is a file in the lambda code base called database.js.  It has all the supported video titles in it.  Do other titles work for you?

3. The Alexa Developer Portal currently does not support MultiModal testing.  To test your skill, you'll need to invoke it from the MutliModal device directly.
